/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package se.alipsa.pd

import javax.xml.bind.JAXBContext

class Deployment {

    String sshUser = null
    String sshPassword = null
    String targetHost
    Ssh ssh

    Deployment(String sshUser, String sshPassword, String targetHost) {
        this.sshUser = sshUser
        this.sshPassword = sshPassword
        this.targetHost = targetHost
        ssh = new Ssh(targetHost, sshUser, sshPassword)
    }

    void createUser(String userName) {

    }

    void createService(String serviceName) {

    }

    void stopService(String serviceName) {

    }

    void startService(String serviceName) {

    }

    /**
     *
     * @param from the url to pull the resource from
     * @param to the target path on the server to put the file on
     */
    void copy(URL from, String to) {

    }

    /**
     *
     * @param from the path to copy the resource from
     * @param to the target path on the server to put the file on
     */
    void copy(String from, String to) {
        ssh.upload(from, to);
    }

    void chown(String file, String userName) {

    }

    void chmod(String file, String mode) {

    }

    String restCall(URL url, String method) {
        return "";
    }
}
