/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package se.alipsa.pd

class ProjectDeployer {

    String sshUser = null;
    String sudoPassword = null;

    ProjectDeployer() {
        if (sshUser == null) {
            System.getProperty("user.name");
        }
    }

    void createUser(String userName) {

    }

    void createService(String serviceName) {

    }

    void stopService(String serviceName) {

    }

    void startService(String serviceName) {

    }

    /**
     *
     * @param from the url to pull the resource from
     * @param to the target path on the server to put the file on
     */
    void copyFile(URL from, String to) {

    }

    void chown(String file, String userName) {

    }

    void chmod(String file, String mode) {

    }

    String restCall(URL url, String method) {
        return "";
    }
}
