/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package se.alipsa.pd

import spock.lang.*

class ProjectDeployerTest extends Specification {

    def setup() {
        println("TODO: start an ssh server")
    }

    def "copy file to server"() {
        println("testing!!!!!!!")
        setup: "temp file with content created"
        def pd = new ProjectDeployer()
        def tempFile = File.createTempFile("test", "txt")
        new FileWriter(tempFile).withCloseable { writer ->
            writer.write("Hello world")
        }
        when: "A file is copied to the server"
        pd.copyFile(new URL("file://" + tempFile.getAbsolutePath()), "/deploy/test.txt")

        then: "TODO: check that the file exists on the ssh server"
        true == false
    }
}
