/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package se.alipsa.pd

import spock.lang.Specification

class ProjectDeployerTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def pd = new ProjectDeployer()

        when:
        def result = pd.someLibraryMethod()

        then:
        result == true
    }
}
